"""Patch 2 (retry): update query_pipeline signature and insert comparison branch + new method."""

with open("rag_orchestrator.py", encoding="utf-8") as f:
    lines = f.readlines()

# ── Step 1: Update query_pipeline signature ───────────────────────────────────
qp_line = next(i for i, l in enumerate(lines) if "    def query_pipeline(" in l)
sig_end = next(i for i in range(qp_line, qp_line + 12) if lines[i].strip() == "):")
assert "target_baseline" in lines[sig_end - 1], f"Unexpected sig end: {repr(lines[sig_end - 1])}"
lines.insert(sig_end, "        priorities: list | None = None,\n")

# ── Step 2: Insert comparison branch after the start_time print line ─────────
qp_line2 = next(i for i, l in enumerate(lines) if "    def query_pipeline(" in l)
start_time_line = next(i for i in range(qp_line2, qp_line2 + 20) if "start_time = time.time()" in lines[i])
print_line = start_time_line + 1
assert "print(" in lines[print_line], f"Expected print, got: {repr(lines[print_line])}"

branch = [
    "\n",
    "        # ── Priority comparison shortcut ─────────────────────────────────────\n",
    "        if priorities and target_baseline and target_competitor:\n",
    "            print(f\"\u2b50 Priorities given \u2014 running structured comparison for [{len(priorities)}] priorities.\")\n",
    "            comparison_answer = self._run_priority_comparison(\n",
    "                user_query, priorities, target_baseline, target_competitor, target_programme\n",
    "            )\n",
    "            if comparison_answer:\n",
    "                sql_docs_cit = self.query_router.execute_sql(\n",
    "                    user_query,\n",
    "                    target_competitor=target_competitor,\n",
    "                    target_programme=target_programme,\n",
    "                    target_baseline=target_baseline,\n",
    "                )\n",
    "                kb_docs_cit = self.knowledge_base_retriever.search(\n",
    "                    user_query, top_k=4,\n",
    "                    allowed_institutions=[target_baseline, target_competitor],\n",
    "                )\n",
    "                all_cit_docs = sql_docs_cit + kb_docs_cit\n",
    "                citations = self._build_citations(all_cit_docs)\n",
    "                self._write_trace_event(user_query, comparison_answer, 0.9, False)\n",
    "                return {\n",
    "                    \"answer\": comparison_answer,\n",
    "                    \"engine_used\": \"Priority Comparison (Gemini)\",\n",
    "                    \"routing_layer\": \"SQL+KB\",\n",
    "                    \"latency_seconds\": round(time.time() - start_time, 3),\n",
    "                    \"sources\": [item.get(\"source\") for item in citations],\n",
    "                    \"citations\": citations,\n",
    "                    \"contexts\": [doc.page_content for doc in all_cit_docs],\n",
    "                    \"confidence_score\": 0.9,\n",
    "                    \"should_abstain\": False,\n",
    "                }\n",
    "\n",
]
lines = lines[:print_line + 1] + branch + lines[print_line + 1:]

# ── Step 3: Insert _run_priority_comparison before query_pipeline ─────────────
qp_line3 = next(i for i, l in enumerate(lines) if "    def query_pipeline(" in l)

method = [
    "\n",
    "    def _run_priority_comparison(\n",
    "        self,\n",
    "        user_query: str,\n",
    "        priorities: list,\n",
    "        target_baseline: str,\n",
    "        target_competitor: str,\n",
    "        target_programme: str | None,\n",
    "    ) -> str | None:\n",
    "        \"\"\"Fetch SQL + KB data for both universities and call Gemini for a priority-by-priority comparison.\"\"\"\n",
    "\n",
    "        sql_docs = self.query_router.execute_sql(\n",
    "            user_query,\n",
    "            target_competitor=target_competitor,\n",
    "            target_programme=target_programme,\n",
    "            target_baseline=target_baseline,\n",
    "        )\n",
    "        baseline_row: dict = {}\n",
    "        competitor_row: dict = {}\n",
    "        for doc in sql_docs:\n",
    "            content = str(getattr(doc, \"page_content\", \"\") or \"\")\n",
    "            if \"Structured Database Results:\" not in content:\n",
    "                continue\n",
    "            try:\n",
    "                rows = json.loads(content.split(\"Structured Database Results:\", 1)[1].strip())\n",
    "                for row in (rows if isinstance(rows, list) else []):\n",
    "                    uni = str(row.get(\"university\") or \"\").lower()\n",
    "                    if uni == target_baseline.lower() and not baseline_row:\n",
    "                        baseline_row = row\n",
    "                    elif uni == target_competitor.lower() and not competitor_row:\n",
    "                        competitor_row = row\n",
    "            except Exception:\n",
    "                pass\n",
    "\n",
    "        if not baseline_row and not competitor_row:\n",
    "            return None\n",
    "\n",
    "        kb_docs = self.knowledge_base_retriever.search(\n",
    "            user_query, top_k=6,\n",
    "            allowed_institutions=[target_baseline, target_competitor],\n",
    "        )\n",
    "        kb_base = \" \".join(\n",
    "            doc.page_content[:300]\n",
    "            for doc in kb_docs\n",
    "            if str((getattr(doc, \"metadata\", {}) or {}).get(\"institution\", \"\")).lower() == target_baseline.lower()\n",
    "        )\n",
    "        kb_comp = \" \".join(\n",
    "            doc.page_content[:300]\n",
    "            for doc in kb_docs\n",
    "            if str((getattr(doc, \"metadata\", {}) or {}).get(\"institution\", \"\")).lower() == target_competitor.lower()\n",
    "        )\n",
    "\n",
    "        def _v(row: dict, key: str, prefix: str = \"\", suffix: str = \"\", decimals: int = 0) -> str:\n",
    "            val = row.get(key)\n",
    "            if val is None:\n",
    "                return \"N/A\"\n",
    "            try:\n",
    "                f = float(val)\n",
    "                return f\"{prefix}{f:,.{decimals}f}{suffix}\" if decimals else f\"{prefix}{f:,.0f}{suffix}\"\n",
    "            except (ValueError, TypeError):\n",
    "                return str(val)\n",
    "\n",
    "        context_blocks = []\n",
    "        for priority in priorities:\n",
    "            p = str(priority).lower()\n",
    "            b: list = []\n",
    "            c: list = []\n",
    "\n",
    "            if \"entry\" in p:\n",
    "                for parts, row in [(b, baseline_row), (c, competitor_row)]:\n",
    "                    parts.append(f\"A-level requirement: {row.get('alevel_requirement') or 'N/A'}\")\n",
    "                    if row.get(\"entry_tariff\"):\n",
    "                        parts.append(f\"Avg entry tariff: {_v(row, 'entry_tariff')} UCAS pts\")\n",
    "                    if row.get(\"pct_entrants_alevel\") is not None:\n",
    "                        parts.append(f\"Entrants via A-level: {_v(row, 'pct_entrants_alevel', suffix='%', decimals=1)}\")\n",
    "                    parts.append(f\"Foundation year: {'Yes' if row.get('has_foundation_year') else 'No'}\")\n",
    "\n",
    "            elif \"curriculum\" in p or \"accredit\" in p:\n",
    "                for parts, row, kb in [(b, baseline_row, kb_base), (c, competitor_row, kb_comp)]:\n",
    "                    parts.append(f\"BCS accredited: {'Yes' if row.get('bcs_accredited') else 'No'}\")\n",
    "                    parts.append(f\"Final year project credits: {row.get('final_year_project_credits') or 'N/A'}\")\n",
    "                    parts.append(f\"Placement year: {'Yes' if row.get('has_placement_year') else 'No'}\")\n",
    "                    parts.append(f\"Year abroad: {'Yes' if row.get('has_year_abroad') else 'No'}\")\n",
    "                    if kb.strip():\n",
    "                        parts.append(f\"Prospectus: {kb.strip()[:250]}\")\n",
    "\n",
    "            elif \"graduate\" in p or \"salary\" in p or \"outcome\" in p:\n",
    "                pound = chr(163)\n",
    "                for parts, row in [(b, baseline_row), (c, competitor_row)]:\n",
    "                    parts.append(f\"Median salary 3yr (LEO): {_v(row, 'median_salary_leo3', prefix=pound)}\")\n",
    "                    parts.append(f\"Median salary 5yr (LEO): {_v(row, 'median_salary_leo5', prefix=pound)}\")\n",
    "                    parts.append(f\"Graduate outcomes salary: {_v(row, 'median_salary_go', prefix=pound)}\")\n",
    "                    if row.get(\"employment_rate_15m\") is not None:\n",
    "                        parts.append(f\"Employment rate 15m: {_v(row, 'employment_rate_15m', suffix='%', decimals=1)}\")\n",
    "                    if row.get(\"pct_professional_managerial\") is not None:\n",
    "                        parts.append(f\"Professional/managerial: {_v(row, 'pct_professional_managerial', suffix='%', decimals=1)}\")\n",
    "\n",
    "            elif \"fee\" in p or \"cost\" in p:\n",
    "                for parts, row in [(b, baseline_row), (c, competitor_row)]:\n",
    "                    parts.append(f\"UK tuition fee: {row.get('tuition_fee_uk') or 'N/A'}\")\n",
    "                    parts.append(f\"International fee: {row.get('tuition_fee_intl') or 'N/A'}\")\n",
    "\n",
    "            elif \"teaching\" in p or \"nss\" in p or \"quality\" in p:\n",
    "                for parts, row in [(b, baseline_row), (c, competitor_row)]:\n",
    "                    if row.get(\"nss_teaching_satisfaction\") is not None:\n",
    "                        parts.append(f\"NSS teaching satisfaction: {_v(row, 'nss_teaching_satisfaction', suffix='%', decimals=1)}\")\n",
    "                    if row.get(\"nss_mental_wellbeing\") is not None:\n",
    "                        parts.append(f\"NSS mental wellbeing: {_v(row, 'nss_mental_wellbeing', suffix='%', decimals=1)}\")\n",
    "                    if row.get(\"nss_facilities_resources\") is not None:\n",
    "                        parts.append(f\"NSS facilities: {_v(row, 'nss_facilities_resources', suffix='%', decimals=1)}\")\n",
    "                    parts.append(f\"TEF overall: {row.get('tef_overall_rating') or 'N/A'}\")\n",
    "                    parts.append(f\"TEF student experience: {row.get('tef_student_experience') or 'N/A'}\")\n",
    "\n",
    "            elif \"rank\" in p:\n",
    "                for parts, row in [(b, baseline_row), (c, competitor_row)]:\n",
    "                    parts.append(f\"Guardian rank: {_v(row, 'guardian_rank', prefix='#') if row.get('guardian_rank') else 'N/A'}\")\n",
    "                    parts.append(f\"CUG rank: {_v(row, 'cug_rank', prefix='#') if row.get('cug_rank') else 'N/A'}\")\n",
    "                    parts.append(f\"QS world rank: {_v(row, 'qs_rank', prefix='#') if row.get('qs_rank') else 'N/A'}\")\n",
    "\n",
    "            if b or c:\n",
    "                label = str(priority).split(\"(\")[0].strip()\n",
    "                context_blocks.append(\n",
    "                    f\"=== {label} ===\\n\"\n",
    "                    f\"{target_baseline}:\\n\" + \"\\n\".join(f\"  - {x}\" for x in b) + \"\\n\"\n",
    "                    + f\"{target_competitor}:\\n\" + \"\\n\".join(f\"  - {x}\" for x in c)\n",
    "                )\n",
    "\n",
    "        if not context_blocks:\n",
    "            return None\n",
    "\n",
    "        context_str = \"\\n\\n\".join(context_blocks)\n",
    "        programme = target_programme or \"Computer Science BSc\"\n",
    "        priority_list = \"\\n\".join(f\"{i+1}. {str(p).split('(')[0].strip()}\" for i, p in enumerate(priorities))\n",
    "\n",
    "        comparison_prompt = (\n",
    "            f\"You are an expert UK university admissions guide tutor.\\n\\n\"\n",
    "            f\"A student is comparing {programme} at {target_baseline} vs {target_competitor}.\\n\\n\"\n",
    "            f\"VERIFIED DATA FROM DATABASE (use ONLY this, do not use outside knowledge):\\n{context_str}\\n\\n\"\n",
    "            f\"Write a structured comparison covering EACH priority below.\\n\"\n",
    "            f\"For EACH priority use this exact format:\\n\"\n",
    "            f\"## [number]. [Priority Name]\\n\"\n",
    "            f\"**{target_baseline}:** bullet facts from data\\n\"\n",
    "            f\"**{target_competitor}:** bullet facts from data\\n\"\n",
    "            f\"**Winner:** [university] \u2014 one sentence reason based on data\\n\\n\"\n",
    "            f\"Priorities:\\n{priority_list}\\n\\n\"\n",
    "            f\"## OVERALL RECOMMENDATION\\n\"\n",
    "            f\"End with a | Priority | Best Choice | Reason | markdown table, then 2\u20133 sentences of tutor advice.\\n\"\n",
    "            f\"Write N/A where data is missing. Do not invent facts.\"\n",
    "        )\n",
    "\n",
    "        gemini_models = self._ensure_gemini_models()\n",
    "        if not gemini_models:\n",
    "            return None\n",
    "\n",
    "        for model_name in gemini_models:\n",
    "            try:\n",
    "                llm = ChatGoogleGenerativeAI(\n",
    "                    model=model_name, temperature=0.1, google_api_key=self.api_key,\n",
    "                )\n",
    "                chain = ChatPromptTemplate.from_messages([\n",
    "                    HumanMessagePromptTemplate.from_template(\"{prompt}\")\n",
    "                ]) | llm | StrOutputParser()\n",
    "                result = chain.invoke({\"prompt\": comparison_prompt})\n",
    "                if isinstance(result, str) and result.strip():\n",
    "                    print(f\"\\u2705 Priority comparison generated with [{model_name}].\")\n",
    "                    return result.strip()\n",
    "            except Exception as exc:\n",
    "                print(f\"\\u26a0\\ufe0f Priority comparison failed with {model_name}: {exc}\")\n",
    "\n",
    "        return None\n",
    "\n",
]

lines = lines[:qp_line3] + method + lines[qp_line3:]

with open("rag_orchestrator.py", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("Patch 2 applied successfully.")
